runtime: python36
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: numpy
  version: latest
- name: random
  version: latest
- name: csv
  version: latest

handlers:
- url: /static
  static_dir: static
  application_readable: TRUE
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /.*
  script: main.app
